/*
Elastic Email REST API

This API is based on the REST API architecture, allowing the user to easily manage their data with this resource-based approach.    Every API call is established on which specific request type (GET, POST, PUT, DELETE) will be used.    The API has a limit of 20 concurrent connections and a hard timeout of 600 seconds per request.    To start using this API, you will need your Access Token (available <a target=\"_blank\" href=\"https://app.elasticemail.com/marketing/settings/new/manage-api\">here</a>). Remember to keep it safe. Required access levels are listed in the given request’s description.    Downloadable library clients can be found in our Github repository <a target=\"_blank\" href=\"https://github.com/ElasticEmail?tab=repositories&q=%22rest+api%22+in%3Areadme\">here</a>

API version: 4.0.0
Contact: support@elasticemail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ElasticEmail

import (
	"encoding/json"
	"fmt"
)

// DomainOwner the model 'DomainOwner'
type DomainOwner string

// List of DomainOwner
const (
	CURRENT DomainOwner = "Current"
	PARENT DomainOwner = "Parent"
)

// All allowed values of DomainOwner enum
var AllowedDomainOwnerEnumValues = []DomainOwner{
	"Current",
	"Parent",
}

func (v *DomainOwner) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := DomainOwner(value)
	for _, existing := range AllowedDomainOwnerEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid DomainOwner", value)
}

// NewDomainOwnerFromValue returns a pointer to a valid DomainOwner
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewDomainOwnerFromValue(v string) (*DomainOwner, error) {
	ev := DomainOwner(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for DomainOwner: valid values are %v", v, AllowedDomainOwnerEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v DomainOwner) IsValid() bool {
	for _, existing := range AllowedDomainOwnerEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to DomainOwner value
func (v DomainOwner) Ptr() *DomainOwner {
	return &v
}

type NullableDomainOwner struct {
	value *DomainOwner
	isSet bool
}

func (v NullableDomainOwner) Get() *DomainOwner {
	return v.value
}

func (v *NullableDomainOwner) Set(val *DomainOwner) {
	v.value = val
	v.isSet = true
}

func (v NullableDomainOwner) IsSet() bool {
	return v.isSet
}

func (v *NullableDomainOwner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDomainOwner(val *DomainOwner) *NullableDomainOwner {
	return &NullableDomainOwner{value: val, isSet: true}
}

func (v NullableDomainOwner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDomainOwner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

