/*
Elastic Email REST API

This API is based on the REST API architecture, allowing the user to easily manage their data with this resource-based approach.    Every API call is established on which specific request type (GET, POST, PUT, DELETE) will be used.    The API has a limit of 20 concurrent connections and a hard timeout of 600 seconds per request.    To start using this API, you will need your Access Token (available <a target=\"_blank\" href=\"https://app.elasticemail.com/marketing/settings/new/manage-api\">here</a>). Remember to keep it safe. Required access levels are listed in the given request’s description.    Downloadable library clients can be found in our Github repository <a target=\"_blank\" href=\"https://github.com/ElasticEmail?tab=repositories&q=%22rest+api%22+in%3Areadme\">here</a>

API version: 4.0.0
Contact: support@elasticemail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ElasticEmail

import (
	"encoding/json"
	"fmt"
)

// CertificateValidationStatus the model 'CertificateValidationStatus'
type CertificateValidationStatus string

// List of CertificateValidationStatus
const (
	ERROR_OCCURED CertificateValidationStatus = "ErrorOccured"
	CERT_NOT_SET CertificateValidationStatus = "CertNotSet"
	VALID CertificateValidationStatus = "Valid"
	NOT_VALID CertificateValidationStatus = "NotValid"
)

// All allowed values of CertificateValidationStatus enum
var AllowedCertificateValidationStatusEnumValues = []CertificateValidationStatus{
	"ErrorOccured",
	"CertNotSet",
	"Valid",
	"NotValid",
}

func (v *CertificateValidationStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := CertificateValidationStatus(value)
	for _, existing := range AllowedCertificateValidationStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid CertificateValidationStatus", value)
}

// NewCertificateValidationStatusFromValue returns a pointer to a valid CertificateValidationStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewCertificateValidationStatusFromValue(v string) (*CertificateValidationStatus, error) {
	ev := CertificateValidationStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for CertificateValidationStatus: valid values are %v", v, AllowedCertificateValidationStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v CertificateValidationStatus) IsValid() bool {
	for _, existing := range AllowedCertificateValidationStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to CertificateValidationStatus value
func (v CertificateValidationStatus) Ptr() *CertificateValidationStatus {
	return &v
}

type NullableCertificateValidationStatus struct {
	value *CertificateValidationStatus
	isSet bool
}

func (v NullableCertificateValidationStatus) Get() *CertificateValidationStatus {
	return v.value
}

func (v *NullableCertificateValidationStatus) Set(val *CertificateValidationStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableCertificateValidationStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableCertificateValidationStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCertificateValidationStatus(val *CertificateValidationStatus) *NullableCertificateValidationStatus {
	return &NullableCertificateValidationStatus{value: val, isSet: true}
}

func (v NullableCertificateValidationStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCertificateValidationStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

