/*
 * Elastic Email REST API
 *
 * This API is based on the REST API architecture, allowing the user to easily manage their data with this resource-based approach.    Every API call is established on which specific request type (GET, POST, PUT, DELETE) will be used.    To start using this API, you will need your Access Token (available <a href=\"https://elasticemail.com/account#/settings/new/manage-api\">here</a>). Remember to keep it safe. Required access levels are listed in the given request’s description.    This is the documentation for REST API. If you’d like to read our legacy documentation regarding Web API v2 click <a href=\"https://api.elasticemail.com/public/help\">here</a>.
 *
 * API version: 4.0.0
 * Contact: support@elasticemail.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ElasticEmail

import (
	"encoding/json"
	"fmt"
)

// EmailValidationStatus the model 'EmailValidationStatus'
type EmailValidationStatus string

// List of EmailValidationStatus
const (
	NONE EmailValidationStatus = "None"
	VALID EmailValidationStatus = "Valid"
	UNKNOWN EmailValidationStatus = "Unknown"
	RISKY EmailValidationStatus = "Risky"
	INVALID EmailValidationStatus = "Invalid"
)

func (v *EmailValidationStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := EmailValidationStatus(value)
	for _, existing := range []EmailValidationStatus{ "None", "Valid", "Unknown", "Risky", "Invalid",   } {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid EmailValidationStatus", value)
}

// Ptr returns reference to EmailValidationStatus value
func (v EmailValidationStatus) Ptr() *EmailValidationStatus {
	return &v
}

type NullableEmailValidationStatus struct {
	value *EmailValidationStatus
	isSet bool
}

func (v NullableEmailValidationStatus) Get() *EmailValidationStatus {
	return v.value
}

func (v *NullableEmailValidationStatus) Set(val *EmailValidationStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableEmailValidationStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableEmailValidationStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmailValidationStatus(val *EmailValidationStatus) *NullableEmailValidationStatus {
	return &NullableEmailValidationStatus{value: val, isSet: true}
}

func (v NullableEmailValidationStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmailValidationStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

