/*
Elastic Email REST API

This API is based on the REST API architecture, allowing the user to easily manage their data with this resource-based approach.    Every API call is established on which specific request type (GET, POST, PUT, DELETE) will be used.    The API has a limit of 20 concurrent connections and a hard timeout of 600 seconds per request.    To start using this API, you will need your Access Token (available <a target='_blank' href='https://app.elasticemail.com/marketing/settings/new/manage-api'>here</a>). Remember to keep it safe. Required access levels are listed in the given request’s description.    Downloadable library clients can be found in our Github repository <a target='_blank' href='https://github.com/ElasticEmail?tab=repositories&q=%22rest+api%22+in%3Areadme'>here</a>

API version: 4.0.0
Contact: support@elasticemail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ElasticEmail

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the WebhookCreatePayload type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebhookCreatePayload{}

// WebhookCreatePayload Create webhook payload
type WebhookCreatePayload struct {
	// Filename
	Name string `json:"Name"`
	// URL of notification.
	URL string `json:"URL"`
	NotifyOncePerEmail *bool `json:"NotifyOncePerEmail,omitempty"`
	NotificationForSent *bool `json:"NotificationForSent,omitempty"`
	NotificationForOpened *bool `json:"NotificationForOpened,omitempty"`
	NotificationForClicked *bool `json:"NotificationForClicked,omitempty"`
	NotificationForUnsubscribed *bool `json:"NotificationForUnsubscribed,omitempty"`
	NotificationForAbuseReport *bool `json:"NotificationForAbuseReport,omitempty"`
	NotificationForError *bool `json:"NotificationForError,omitempty"`
}

type _WebhookCreatePayload WebhookCreatePayload

// NewWebhookCreatePayload instantiates a new WebhookCreatePayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebhookCreatePayload(name string, uRL string) *WebhookCreatePayload {
	this := WebhookCreatePayload{}
	this.Name = name
	this.URL = uRL
	return &this
}

// NewWebhookCreatePayloadWithDefaults instantiates a new WebhookCreatePayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebhookCreatePayloadWithDefaults() *WebhookCreatePayload {
	this := WebhookCreatePayload{}
	return &this
}

// GetName returns the Name field value
func (o *WebhookCreatePayload) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *WebhookCreatePayload) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *WebhookCreatePayload) SetName(v string) {
	o.Name = v
}

// GetURL returns the URL field value
func (o *WebhookCreatePayload) GetURL() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.URL
}

// GetURLOk returns a tuple with the URL field value
// and a boolean to check if the value has been set.
func (o *WebhookCreatePayload) GetURLOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.URL, true
}

// SetURL sets field value
func (o *WebhookCreatePayload) SetURL(v string) {
	o.URL = v
}

// GetNotifyOncePerEmail returns the NotifyOncePerEmail field value if set, zero value otherwise.
func (o *WebhookCreatePayload) GetNotifyOncePerEmail() bool {
	if o == nil || IsNil(o.NotifyOncePerEmail) {
		var ret bool
		return ret
	}
	return *o.NotifyOncePerEmail
}

// GetNotifyOncePerEmailOk returns a tuple with the NotifyOncePerEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookCreatePayload) GetNotifyOncePerEmailOk() (*bool, bool) {
	if o == nil || IsNil(o.NotifyOncePerEmail) {
		return nil, false
	}
	return o.NotifyOncePerEmail, true
}

// HasNotifyOncePerEmail returns a boolean if a field has been set.
func (o *WebhookCreatePayload) HasNotifyOncePerEmail() bool {
	if o != nil && !IsNil(o.NotifyOncePerEmail) {
		return true
	}

	return false
}

// SetNotifyOncePerEmail gets a reference to the given bool and assigns it to the NotifyOncePerEmail field.
func (o *WebhookCreatePayload) SetNotifyOncePerEmail(v bool) {
	o.NotifyOncePerEmail = &v
}

// GetNotificationForSent returns the NotificationForSent field value if set, zero value otherwise.
func (o *WebhookCreatePayload) GetNotificationForSent() bool {
	if o == nil || IsNil(o.NotificationForSent) {
		var ret bool
		return ret
	}
	return *o.NotificationForSent
}

// GetNotificationForSentOk returns a tuple with the NotificationForSent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookCreatePayload) GetNotificationForSentOk() (*bool, bool) {
	if o == nil || IsNil(o.NotificationForSent) {
		return nil, false
	}
	return o.NotificationForSent, true
}

// HasNotificationForSent returns a boolean if a field has been set.
func (o *WebhookCreatePayload) HasNotificationForSent() bool {
	if o != nil && !IsNil(o.NotificationForSent) {
		return true
	}

	return false
}

// SetNotificationForSent gets a reference to the given bool and assigns it to the NotificationForSent field.
func (o *WebhookCreatePayload) SetNotificationForSent(v bool) {
	o.NotificationForSent = &v
}

// GetNotificationForOpened returns the NotificationForOpened field value if set, zero value otherwise.
func (o *WebhookCreatePayload) GetNotificationForOpened() bool {
	if o == nil || IsNil(o.NotificationForOpened) {
		var ret bool
		return ret
	}
	return *o.NotificationForOpened
}

// GetNotificationForOpenedOk returns a tuple with the NotificationForOpened field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookCreatePayload) GetNotificationForOpenedOk() (*bool, bool) {
	if o == nil || IsNil(o.NotificationForOpened) {
		return nil, false
	}
	return o.NotificationForOpened, true
}

// HasNotificationForOpened returns a boolean if a field has been set.
func (o *WebhookCreatePayload) HasNotificationForOpened() bool {
	if o != nil && !IsNil(o.NotificationForOpened) {
		return true
	}

	return false
}

// SetNotificationForOpened gets a reference to the given bool and assigns it to the NotificationForOpened field.
func (o *WebhookCreatePayload) SetNotificationForOpened(v bool) {
	o.NotificationForOpened = &v
}

// GetNotificationForClicked returns the NotificationForClicked field value if set, zero value otherwise.
func (o *WebhookCreatePayload) GetNotificationForClicked() bool {
	if o == nil || IsNil(o.NotificationForClicked) {
		var ret bool
		return ret
	}
	return *o.NotificationForClicked
}

// GetNotificationForClickedOk returns a tuple with the NotificationForClicked field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookCreatePayload) GetNotificationForClickedOk() (*bool, bool) {
	if o == nil || IsNil(o.NotificationForClicked) {
		return nil, false
	}
	return o.NotificationForClicked, true
}

// HasNotificationForClicked returns a boolean if a field has been set.
func (o *WebhookCreatePayload) HasNotificationForClicked() bool {
	if o != nil && !IsNil(o.NotificationForClicked) {
		return true
	}

	return false
}

// SetNotificationForClicked gets a reference to the given bool and assigns it to the NotificationForClicked field.
func (o *WebhookCreatePayload) SetNotificationForClicked(v bool) {
	o.NotificationForClicked = &v
}

// GetNotificationForUnsubscribed returns the NotificationForUnsubscribed field value if set, zero value otherwise.
func (o *WebhookCreatePayload) GetNotificationForUnsubscribed() bool {
	if o == nil || IsNil(o.NotificationForUnsubscribed) {
		var ret bool
		return ret
	}
	return *o.NotificationForUnsubscribed
}

// GetNotificationForUnsubscribedOk returns a tuple with the NotificationForUnsubscribed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookCreatePayload) GetNotificationForUnsubscribedOk() (*bool, bool) {
	if o == nil || IsNil(o.NotificationForUnsubscribed) {
		return nil, false
	}
	return o.NotificationForUnsubscribed, true
}

// HasNotificationForUnsubscribed returns a boolean if a field has been set.
func (o *WebhookCreatePayload) HasNotificationForUnsubscribed() bool {
	if o != nil && !IsNil(o.NotificationForUnsubscribed) {
		return true
	}

	return false
}

// SetNotificationForUnsubscribed gets a reference to the given bool and assigns it to the NotificationForUnsubscribed field.
func (o *WebhookCreatePayload) SetNotificationForUnsubscribed(v bool) {
	o.NotificationForUnsubscribed = &v
}

// GetNotificationForAbuseReport returns the NotificationForAbuseReport field value if set, zero value otherwise.
func (o *WebhookCreatePayload) GetNotificationForAbuseReport() bool {
	if o == nil || IsNil(o.NotificationForAbuseReport) {
		var ret bool
		return ret
	}
	return *o.NotificationForAbuseReport
}

// GetNotificationForAbuseReportOk returns a tuple with the NotificationForAbuseReport field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookCreatePayload) GetNotificationForAbuseReportOk() (*bool, bool) {
	if o == nil || IsNil(o.NotificationForAbuseReport) {
		return nil, false
	}
	return o.NotificationForAbuseReport, true
}

// HasNotificationForAbuseReport returns a boolean if a field has been set.
func (o *WebhookCreatePayload) HasNotificationForAbuseReport() bool {
	if o != nil && !IsNil(o.NotificationForAbuseReport) {
		return true
	}

	return false
}

// SetNotificationForAbuseReport gets a reference to the given bool and assigns it to the NotificationForAbuseReport field.
func (o *WebhookCreatePayload) SetNotificationForAbuseReport(v bool) {
	o.NotificationForAbuseReport = &v
}

// GetNotificationForError returns the NotificationForError field value if set, zero value otherwise.
func (o *WebhookCreatePayload) GetNotificationForError() bool {
	if o == nil || IsNil(o.NotificationForError) {
		var ret bool
		return ret
	}
	return *o.NotificationForError
}

// GetNotificationForErrorOk returns a tuple with the NotificationForError field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookCreatePayload) GetNotificationForErrorOk() (*bool, bool) {
	if o == nil || IsNil(o.NotificationForError) {
		return nil, false
	}
	return o.NotificationForError, true
}

// HasNotificationForError returns a boolean if a field has been set.
func (o *WebhookCreatePayload) HasNotificationForError() bool {
	if o != nil && !IsNil(o.NotificationForError) {
		return true
	}

	return false
}

// SetNotificationForError gets a reference to the given bool and assigns it to the NotificationForError field.
func (o *WebhookCreatePayload) SetNotificationForError(v bool) {
	o.NotificationForError = &v
}

func (o WebhookCreatePayload) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebhookCreatePayload) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["Name"] = o.Name
	toSerialize["URL"] = o.URL
	if !IsNil(o.NotifyOncePerEmail) {
		toSerialize["NotifyOncePerEmail"] = o.NotifyOncePerEmail
	}
	if !IsNil(o.NotificationForSent) {
		toSerialize["NotificationForSent"] = o.NotificationForSent
	}
	if !IsNil(o.NotificationForOpened) {
		toSerialize["NotificationForOpened"] = o.NotificationForOpened
	}
	if !IsNil(o.NotificationForClicked) {
		toSerialize["NotificationForClicked"] = o.NotificationForClicked
	}
	if !IsNil(o.NotificationForUnsubscribed) {
		toSerialize["NotificationForUnsubscribed"] = o.NotificationForUnsubscribed
	}
	if !IsNil(o.NotificationForAbuseReport) {
		toSerialize["NotificationForAbuseReport"] = o.NotificationForAbuseReport
	}
	if !IsNil(o.NotificationForError) {
		toSerialize["NotificationForError"] = o.NotificationForError
	}
	return toSerialize, nil
}

func (o *WebhookCreatePayload) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"Name",
		"URL",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWebhookCreatePayload := _WebhookCreatePayload{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWebhookCreatePayload)

	if err != nil {
		return err
	}

	*o = WebhookCreatePayload(varWebhookCreatePayload)

	return err
}

type NullableWebhookCreatePayload struct {
	value *WebhookCreatePayload
	isSet bool
}

func (v NullableWebhookCreatePayload) Get() *WebhookCreatePayload {
	return v.value
}

func (v *NullableWebhookCreatePayload) Set(val *WebhookCreatePayload) {
	v.value = val
	v.isSet = true
}

func (v NullableWebhookCreatePayload) IsSet() bool {
	return v.isSet
}

func (v *NullableWebhookCreatePayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebhookCreatePayload(val *WebhookCreatePayload) *NullableWebhookCreatePayload {
	return &NullableWebhookCreatePayload{value: val, isSet: true}
}

func (v NullableWebhookCreatePayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebhookCreatePayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


