/*
 * Elastic Email REST API
 *
 * This API is based on the REST API architecture, allowing the user to easily manage their data with this resource-based approach.    Every API call is established on which specific request type (GET, POST, PUT, DELETE) will be used.    To start using this API, you will need your Access Token (available <a href=\"https://elasticemail.com/account#/settings/new/manage-api\">here</a>). Remember to keep it safe. Required access levels are listed in the given request’s description.    This is the documentation for REST API. If you’d like to read our legacy documentation regarding Web API v2 click <a href=\"https://api.elasticemail.com/public/help\">here</a>.
 *
 * API version: 4.0.0
 * Contact: support@elasticemail.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ElasticEmail

import (
	"encoding/json"
	"fmt"
)

// TemplateScopeType Visibility of a template
type TemplateScopeType string

// List of TemplateScopeType
const (
	PERSONAL TemplateScopeType = "Personal"
	GLOBAL TemplateScopeType = "Global"
	DRAFT TemplateScopeType = "Draft"
)

func (v *TemplateScopeType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := TemplateScopeType(value)
	for _, existing := range []TemplateScopeType{ "Personal", "Global", "Draft",   } {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid TemplateScopeType", value)
}

// Ptr returns reference to TemplateScopeType value
func (v TemplateScopeType) Ptr() *TemplateScopeType {
	return &v
}

type NullableTemplateScopeType struct {
	value *TemplateScopeType
	isSet bool
}

func (v NullableTemplateScopeType) Get() *TemplateScopeType {
	return v.value
}

func (v *NullableTemplateScopeType) Set(val *TemplateScopeType) {
	v.value = val
	v.isSet = true
}

func (v NullableTemplateScopeType) IsSet() bool {
	return v.isSet
}

func (v *NullableTemplateScopeType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTemplateScopeType(val *TemplateScopeType) *NullableTemplateScopeType {
	return &NullableTemplateScopeType{value: val, isSet: true}
}

func (v NullableTemplateScopeType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTemplateScopeType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

